gems:
  - aasm
  - authlogic
  - formtastic
  - geokit
  - googlecharts
  - haml
  - inherited_resources
  - interfacelift
  - lockdown
  - michel-dry_scaffold
  - paperclip
  - prawn
  - rest-client
  - searchlogic
  - will_paginate
  - settingslogic
  - validation_reflection
plugins:
  - authlogic_openid
  - backgroundrb
  - geokit-rails
javascripts:
  - jquery