gems:
  - authlogic
  - formtastic
  - geokit
  - googlecharts
  - haml
  - inherited_resources
  - lockdown
  - paperclip
  - prawn
  - rest-client
  - searchlogic
  - will_paginate
  - settingslogic
  - michel-dry_scaffold
plugins:
  - authlogic_openid
  - geokit-rails
javascripts:
  - jquery